/*
Data Access Layer
 */

package project1.example.codeSpringBoot.student;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface StudentRepository extends JpaRepository<Student, Long> {

    /*
 Long by ID is used here, and It will be generated by default, that is why,
 we have used generics and used Student and Long(ID was declared Long)
 */

}
